sudo: true                  # Required to install packages

services:
  - docker

language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

install:
  - composer self-update
  - composer up

script:
  - make test
